// <auto-generated />
namespace Trabalho_Final_MOD_17E.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class carregamentos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(carregamentos));
        
        string IMigrationMetadata.Id
        {
            get { return "202303071423005_carregamentos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
